baseURL = "https://tgelez.github.io/"
languageCode = "en-us"
title = "tgelez"
theme = "xmin"
enableEmoji = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Cellar"
    url = "/cellar/"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
